import type { RiskClass, ToolEffect, ToolPolicy } from "./capability-broker.js";
import type { ExecutionRootAccess, PathOperation } from "./path-policy.js";

function policy(
  riskClasses: RiskClass[],
  approval: "none" | "user",
  effects: ToolEffect[],
  pathOperations: PathOperation[] = [],
  executionRootAccess?: ExecutionRootAccess
): ToolPolicy {
  return Object.freeze({
    riskClasses: Object.freeze([...riskClasses]),
    approval,
    effects: Object.freeze([...effects]),
    pathOperations: Object.freeze([...pathOperations]),
    executionRootAccess,
  });
}

export const STATIC_TOOL_POLICIES: Readonly<Record<string, ToolPolicy>> = Object.freeze({
  list_directory: policy(["read"], "none", ["filesystem"], ["read-directory"]),
  read_file: policy(["read"], "none", ["filesystem"], ["read-file"]),
  search_files: policy(["read"], "none", ["filesystem"], ["search-tree"]),
  write_file: policy(["write"], "user", ["filesystem"], ["create-file", "replace-file"]),
  edit_file: policy(["read", "write"], "user", ["filesystem"], ["replace-file"]),
  grep: policy(["read"], "none", ["filesystem"], ["search-tree"]),
  create_docx: policy(["write"], "user", ["filesystem"], ["create-file", "replace-file"]),
  create_xlsx: policy(["write"], "user", ["filesystem"], ["create-file", "replace-file"]),
  execute_command: policy(["read", "write", "network", "process", "control"], "user", ["filesystem", "network", "process", "control"], ["initial-cwd"], "read-write"),
  shell_start: policy(["read", "write", "process", "control"], "user", ["filesystem", "process", "control"], ["initial-cwd"], "read-write"),
  shell_input: policy(["read", "write", "network", "process", "control"], "user", ["filesystem", "network", "process", "control"]),
  shell_output: policy(["read", "process", "control"], "none", ["process", "control"]),
  shell_list: policy(["read", "process", "control"], "none", ["process", "control"]),
  shell_kill: policy(["process", "control"], "user", ["process", "control"]),
  fetch_url: policy(["read", "network"], "none", ["network"]),
  remember: policy(["read", "write"], "none", ["filesystem"]),
  recall: policy(["read"], "none", ["filesystem"]),
  list_memories: policy(["read"], "none", ["filesystem"]),
  create_tasks: policy(["write"], "none", ["filesystem"]),
  update_task: policy(["write"], "none", ["filesystem"]),
  list_tasks: policy(["read"], "none", ["filesystem"]),
  script: policy(["read", "write", "network", "process", "control"], "user", ["filesystem", "network", "process", "control"], ["initial-cwd"], "read-write"),
  get_current_time: policy(["read"], "none", []),
  cron_list: policy(["read", "control"], "none", ["filesystem", "control"]),
  inspect: policy(["read"], "none", ["filesystem"]),
  graph: policy(["read"], "none", ["filesystem"]),
  web_search: policy(["read", "network"], "none", ["network"]),
  download: policy(["write", "network"], "user", ["filesystem", "network"], ["create-file", "replace-file"]),
  ask_user: policy(["control"], "none", ["control"]),
  oracle_save: policy(["read", "write"], "user", ["filesystem"], ["search-tree"]),
  oracle_status: policy(["read", "control"], "none", ["filesystem", "control"]),
  playbook_list: policy(["read", "write"], "none", ["filesystem"]),
  playbook_create: policy(["write", "control"], "user", ["filesystem", "control"]),
  playbook_status: policy(["read", "control"], "none", ["control"]),
  link_discover: policy(["read", "control"], "none", ["control"]),
  link_peek: policy(["read", "control"], "none", ["control"]),
  link_post: policy(["write", "control"], "user", ["control"]),
  poll_subscribe: policy(["read", "control"], "user", ["filesystem", "control"], ["watch-directory"]),
  poll_unsubscribe: policy(["control"], "none", ["control"]),
  poll_list: policy(["read", "control"], "none", ["control"]),
  supervise: policy(["read", "control"], "none", ["control"]),
  memo_add: policy(["write", "control"], "none", ["filesystem", "control"]),
  memo_list: policy(["read"], "none", ["filesystem"]),
  memo_done: policy(["write"], "none", ["filesystem"]),
  mascot_notify: policy(["control"], "none", ["control"]),
  search_tools: policy(["read", "control"], "none", ["control"]),
  image_helper: policy(["read", "network"], "user", ["filesystem", "network"], ["read-file"]),
  read_repo: policy(["read", "process"], "none", ["filesystem", "process"], ["search-tree", "initial-cwd"]),
});

export const RUNTIME_TOOL_POLICIES: Readonly<Record<string, ToolPolicy>> = Object.freeze({
  cron_schedule: policy(["write", "control"], "user", ["filesystem", "control"]),
  cron_cancel: policy(["read", "write", "control"], "user", ["filesystem", "control"]),
  subagent: policy(["read", "write", "network", "process", "control"], "user", ["filesystem", "network", "process", "control"]),
  curate: policy(["read", "network", "control"], "none", ["network", "control"]),
  consolidate: policy(["read", "write", "network"], "none", ["filesystem", "network"]),
  oracle_query: policy(["read", "network"], "none", ["filesystem", "network"]),
  muse: policy(["read", "network"], "none", ["network"]),
  playbook_execute: policy(["read", "write", "network", "process", "control"], "user", ["filesystem", "network", "process", "control"]),
  playbook_abort: policy(["control"], "user", ["control"]),
  save_persona: policy(["read", "write", "control"], "user", ["filesystem", "control"]),
});

export const DIRECT_OPERATION_POLICIES: Readonly<Record<string, ToolPolicy>> = Object.freeze({
  "terminal:list": policy(["read", "control"], "none", ["control"]),
  "terminal:start": policy(["read", "write", "process", "control"], "none", ["filesystem", "process", "control"], ["initial-cwd"], "read-write"),
  "terminal:output": policy(["read", "process", "control"], "none", ["process", "control"]),
  "terminal:input": policy(["read", "write", "network", "process", "control"], "none", ["filesystem", "network", "process", "control"]),
  "terminal:clear": policy(["control"], "none", ["control"]),
  "terminal:kill": policy(["process", "control"], "none", ["process", "control"]),
  "terminal:close": policy(["process", "control"], "none", ["process", "control"]),
  "terminal:subscribe": policy(["read", "process", "control"], "none", ["process", "control"]),
  "file:roots": policy(["read", "control"], "none", ["filesystem", "control"]),
  "file:list": policy(["read", "control"], "none", ["filesystem", "control"]),
  "file:preview": policy(["read", "control"], "none", ["filesystem", "control"]),
  "file:resolve": policy(["read", "control"], "none", ["filesystem", "control"]),
  "file:content": policy(["read", "control"], "none", ["filesystem", "control"]),
  "file:reveal": policy(["read", "process", "control"], "none", ["filesystem", "process", "control"]),
  "supervisor:status": policy(["read", "control"], "none", ["control"]),
  "supervisor:update": policy(["control"], "user", ["control"]),
});
